apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: backend
          image: hello-world
          ports:
            - containerPort: 8080
